/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is up. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password login; sets gf_sid cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Logged in. Response sets Set-Cookie: gf_sid. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke current session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session revoked. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged-in user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List players (admin only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All users including disabled. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** Create player (admin only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserRequest"];
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update own profile / password */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSelfRequest"];
                };
            };
            responses: {
                /** @description Updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
            };
        };
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Admin edit of a user */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateUserRequest"];
                };
            };
            responses: {
                /** @description Updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin-assigned password reset */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description Password updated. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List nights visible to the caller */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Admin sees all; player sees only nights they're a member of. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NightSummary"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create a night (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateNightRequest"];
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NightDetail"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nights/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        /** Full night detail */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Night + players + activity. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NightDetail"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Hard-delete an open night (admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        /** Edit metadata (admin, open only) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateNightRequest"];
                };
            };
            responses: {
                /** @description Updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NightDetail"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        trace?: never;
    };
    "/nights/{id}/players": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a player to an open night */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddPlayerRequest"];
                };
            };
            responses: {
                /** @description Added. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nights/{id}/players/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
                uid: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a player (rejected if they have activity) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["Uuid"];
                    uid: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nights/{id}/buy-ins": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a buy-in */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBuyInRequest"];
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BuyIn"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nights/{id}/buy-ins/{buy_in_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
                buy_in_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a buy-in (open night only) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["Uuid"];
                    buy_in_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nights/{id}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record an IOU trade */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTradeRequest"];
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Trade"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nights/{id}/trades/{trade_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
                trade_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a trade (open night only) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["Uuid"];
                    trade_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nights/{id}/cash-outs/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
                uid: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        /** Upsert a player's cash-out */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["Uuid"];
                    uid: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpsertCashOutRequest"];
                };
            };
            responses: {
                /** @description Current cash-out. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CashOut"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nights/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute and persist the settlement */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Closed. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SettlementResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nights/{id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen a closed night; discards stored settlement */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reopened. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nights/{id}/settlement": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        /** Stored settlement for a closed night */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Balances and transfers. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SettlementResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nights/{id}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        /** Per-night ranking */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ranked entries. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeaderboardEntry"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lifetime leaderboard across closed nights */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ranked entries. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeaderboardEntry"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        Uuid: string;
        /** Format: date-time */
        Timestamp: string;
        /** Format: date */
        DateOnly: string;
        /**
         * Format: int64
         * @description Integer cents. Never a float.
         */
        Cents: number;
        ErrorEnvelope: {
            error: {
                /** @description Stable snake_case code clients can switch on. */
                code: string;
                /** @description Human-readable, already localized if possible. */
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        /** @enum {string} */
        Role: "admin" | "player";
        User: {
            id: components["schemas"]["Uuid"];
            /** Format: email */
            email: string;
            display_name: string;
            role: components["schemas"]["Role"];
            created_at: components["schemas"]["Timestamp"];
            /** Format: date-time */
            disabled_at?: string | null;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            git_sha?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        CreateUserRequest: {
            /** Format: email */
            email: string;
            display_name: string;
            password: string;
            role: components["schemas"]["Role"];
        };
        UpdateUserRequest: {
            display_name?: string;
            role?: components["schemas"]["Role"];
            /** Format: date-time */
            disabled_at?: string | null;
        };
        UpdateSelfRequest: {
            display_name?: string;
            current_password?: string;
            new_password?: string;
        };
        ResetPasswordRequest: {
            new_password: string;
        };
        /** @enum {string} */
        NightStatus: "open" | "closed";
        NightSummary: {
            id: components["schemas"]["Uuid"];
            title: string;
            played_on: components["schemas"]["DateOnly"];
            status: components["schemas"]["NightStatus"];
            cents_per_chip: number;
            /** @default EUR */
            currency: string;
            opened_at: components["schemas"]["Timestamp"];
            /** Format: date-time */
            closed_at?: string | null;
            player_count: number;
        };
        BuyIn: {
            id: components["schemas"]["Uuid"];
            night_id: components["schemas"]["Uuid"];
            user_id: components["schemas"]["Uuid"];
            amount_cents: components["schemas"]["Cents"];
            /** Format: int64 */
            chips: number;
            created_at: components["schemas"]["Timestamp"];
        };
        Trade: {
            id: components["schemas"]["Uuid"];
            night_id: components["schemas"]["Uuid"];
            chip_giver_id: components["schemas"]["Uuid"];
            chip_receiver_id: components["schemas"]["Uuid"];
            /** Format: int64 */
            chips: number;
            amount_cents_owed: components["schemas"]["Cents"];
            created_at: components["schemas"]["Timestamp"];
        };
        CashOut: {
            id: components["schemas"]["Uuid"];
            night_id: components["schemas"]["Uuid"];
            user_id: components["schemas"]["Uuid"];
            /** Format: int64 */
            chips: number;
            created_at: components["schemas"]["Timestamp"];
        };
        NightDetail: {
            night: components["schemas"]["NightSummary"];
            players: components["schemas"]["User"][];
            buy_ins: components["schemas"]["BuyIn"][];
            trades: components["schemas"]["Trade"][];
            cash_outs: components["schemas"]["CashOut"][];
            notes?: string | null;
        };
        CreateNightRequest: {
            title: string;
            played_on: components["schemas"]["DateOnly"];
            cents_per_chip: number;
            /** @default EUR */
            currency: string;
            player_ids: components["schemas"]["Uuid"][];
            notes?: string | null;
        };
        UpdateNightRequest: {
            title?: string;
            played_on?: components["schemas"]["DateOnly"];
            notes?: string | null;
        };
        AddPlayerRequest: {
            user_id: components["schemas"]["Uuid"];
        };
        CreateBuyInRequest: {
            user_id: components["schemas"]["Uuid"];
            amount_cents: components["schemas"]["Cents"];
            /** Format: int64 */
            chips: number;
        };
        CreateTradeRequest: {
            chip_giver_id: components["schemas"]["Uuid"];
            chip_receiver_id: components["schemas"]["Uuid"];
            /** Format: int64 */
            chips: number;
            amount_cents_owed: components["schemas"]["Cents"];
        };
        UpsertCashOutRequest: {
            /** Format: int64 */
            chips: number;
        };
        SettlementBalance: {
            user_id: components["schemas"]["Uuid"];
            net_cents: components["schemas"]["Cents"];
        };
        SettlementTransfer: {
            id: components["schemas"]["Uuid"];
            from_user_id: components["schemas"]["Uuid"];
            to_user_id: components["schemas"]["Uuid"];
            amount_cents: components["schemas"]["Cents"];
            seq: number;
        };
        SettlementResponse: {
            night_id: components["schemas"]["Uuid"];
            computed_at: components["schemas"]["Timestamp"];
            algo_version: number;
            balances: components["schemas"]["SettlementBalance"][];
            transfers: components["schemas"]["SettlementTransfer"][];
        };
        LeaderboardEntry: {
            user_id: components["schemas"]["Uuid"];
            display_name: string;
            net_cents: components["schemas"]["Cents"];
            nights_played: number;
        };
    };
    responses: {
        /** @description Not authenticated. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated but not authorized. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description State conflict (e.g. racing close, missing cash-outs, unbalanced ledger). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Request body failed validation. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Too many requests; see Retry-After header. */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
